development:
  adapter: mysql2
  host: localhost
  database: itu_sso_development
  username: root
  password:

test:
  adapter: mysql2
  host: localhost
  database: itu_sso_development_test
  username: root
  password:
